package io.github.liumaishenjian.ccjava.domain.settings;

/** 严格 Settings v1 解析器可公开的固定失败分类。 @since 0.8.0 */
public enum ConfigurationDiagnosticCode {
    /** JSON 语法无效或有尾随 token。 */ MALFORMED_JSON,
    /** 字节数量超限。 */ BYTE_LIMIT,
    /** 嵌套深度超限。 */ DEPTH_LIMIT,
    /** Object 成员数量超限。 */ MEMBER_LIMIT,
    /** Array 元素数量超限。 */ LIST_LIMIT,
    /** 字符串长度超限。 */ STRING_LIMIT,
    /** 根节点不是 Object。 */ ROOT_NOT_OBJECT,
    /** schemaVersion 不是第一个成员。 */ SCHEMA_VERSION_FIRST,
    /** schemaVersion 不支持。 */ SCHEMA_VERSION_INVALID,
    /** 同一 Object 出现重复成员名。 */ DUPLICATE_KEY,
    /** 出现未声明字段。 */ UNKNOWN_FIELD,
    /** 字段 JSON 类型错误。 */ INVALID_TYPE,
    /** 标量值不符合约束。 */ INVALID_VALUE,
    /** 引用了未注册 Tool。 */ UNSUPPORTED_TOOL,
    /** 权限规则不受支持。 */ UNSUPPORTED_RULE,
    /** 出现凭证类字段。 */ FORBIDDEN_CREDENTIAL_FIELD,
    /** 出现端点类字段。 */ FORBIDDEN_ENDPOINT_FIELD,
    /** 文件解析器收到只能由程序构造的覆盖来源。 */ UNSUPPORTED_FILE_SOURCE,
    /** 合并输入未按固定低到高来源顺序提供。 */ INVALID_SOURCE_ORDER,
    /** 同一来源在一次原子合并中重复出现。 */ DUPLICATE_SOURCE,
    /** 来源声明了该来源类别不允许承载的字段。 */ FORBIDDEN_SOURCE_FIELD,
    /** 规则删除目标不存在，不能提交部分合并结果。 */ MISSING_RULE_REMOVAL,
    /** 可选 Settings 文件不存在。 */ MISSING_FILE,
    /** 固定来源不能在不泄露细节的前提下读取。 */ UNREADABLE_FILE,
    /** 固定来源是链接、重解析点、非普通文件或发生边界逃逸。 */ UNSAFE_FILE,
    /** 读取前后文件 identity、真实路径、大小或修改时间发生变化。 */ IDENTITY_CHANGED,
    /** Project local 文件未被 Git 明确判定为忽略。 */ LOCAL_NOT_GITIGNORED,
    /** Project local 文件的 Git 忽略检查超时、启动失败或输出不可信。 */ LOCAL_GIT_CHECK_FAILED,
    /** 刷新在候选完成前被取消。 */ CANCELLED,
    /** 刷新候选基于陈旧发布版本，不能覆盖新的 last-known-good。 */ CAS_CONFLICT,
    /** 本进程内 Settings 发布版本已耗尽，不能安全递增。 */ REVISION_EXHAUSTED
}
